Support Elm releases on Github

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+bintray_versions='0.15.1 0.16.0 0.16 0.17.1 0.18.0 master'
 install_elm() {
   local install_type=$1
   local version=$2
@@ -19,7 +19,12 @@ install_elm() {
   # we don't want to disturb current working dir
   (
     mkdir -p $install_path/bin
-    tar zxf $source_path -C $install_path/bin --strip-components=1 || exit 1
+    if [[ " $bintray_versions " =~ " $version " ]]
+    then
+      tar zxf $source_path -C $install_path/bin --strip-components=1 || exit 1
+    else
+      tar zxf $source_path -C $install_path/bin || exit 1
+    fi
   )
 }
 
@@ -51,7 +56,7 @@ get_download_file_path() {
   echo "$tmp_download_dir/$pkg_name"
 }
 
-get_platform() {
+get_platform_pre_19() {
   local os=$(uname -s | tr '[A-Z]' '[a-z]')
 
   if [ "darwin" == "$os" ]; then
@@ -70,6 +75,25 @@ get_platform() {
   exit 1
 }
 
+get_platform_post_19() {
+  local os=$(uname -s | tr '[A-Z]' '[a-z]')
+
+  if [ "darwin" == "$os" ]; then
+    echo "mac"
+    return 0
+  fi
+
+  local machine=$(uname -m)
+  if [ "linux" == "$os" ]; then
+    echo "linux"
+    return 0
+  fi
+
+  echo "Could not determine OS platform."
+  echo "Please open a bug report for asdf-elm"
+  exit 1
+}
+
 
 get_download_url() {
   local install_type=$1
@@ -77,7 +101,12 @@ get_download_url() {
 
   if [ "$install_type" == "version" ]
   then
-    echo "https://dl.bintray.com/elmlang/elm-platform/$version/$(get_platform).tar.gz"
+    if [[ " $bintray_versions " =~ " $version " ]]
+    then
+      echo "https://dl.bintray.com/elmlang/elm-platform/$version/$(get_platform_pre_19).tar.gz"
+    else
+      echo "https://github.com/elm/compiler/releases/download/$version/binaries-for-$(get_platform_post_19).tar.gz"
+    fi
   else
     echo "asdf-elm: Can only install versioned binaries."
     echo "If you want to install another version from source, read:"
